/*

 BACKGROUNDTILES.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : C:\Users\CRUSADE\Downloads\gbtd22\tiles\cave01.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BackgroundTilesWidth 13
#define BackgroundTilesHeight 1
#define BackgroundTilesBank 0

unsigned char BackgroundTiles[] =
{
  0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x0A,0x0B,0x0C
};

/* End of BACKGROUNDTILES.C */
