/*

 DEFAULTMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : C:\Users\CRUSADE\Downloads\gbtd22\tiles\cave01.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define defaultMapWidth 32
#define defaultMapHeight 32
#define defaultMapBank 0

extern unsigned char defaultMap[];

/* End of DEFAULTMAP.H */
