/*

 INSECTOR1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 9 x 9
   Tile set      : C:\Users\CRUSADE\Downloads\gbtd22\tiles\cave01.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define inSector1Width 9
#define inSector1Height 9
#define inSector1Bank 0

extern unsigned char inSector1[];

/* End of INSECTOR1.H */
