/*

 TESTMAP3.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : C:\Users\CRUSADE\Downloads\gbtd22\tiles\cave01.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define testmap3Width 32
#define testmap3Height 32
#define testmap3Bank 0

extern unsigned char testmap3[];

/* End of TESTMAP3.H */
